Forms, pipes and directives
mnstrdm/angular-fundamentals-template pull request #2
Opened 2024-10-06 22:09 UTC by mnstrdm

Created Login, Registration, and Course creation/edit forms.
Create pipes to transform duration and creation date.
Create a custom directive to validate e-mail.

2024-10-08 09:08 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.html
A few things on functionality and UI those need update:
- A single character is added to title and/or description and the error message is 'required'. Probably it would be better to use the minimum character length validation and display that message to the user.
- When I enter some negative values into the duration field (that is obviously invalid), then it looks strange on the UI. You should update the duration pipe logic.
- New author field with a single character entered is giving the following error msg. Please update the template with appropriate error messages. Also add the warning color, too.
![image](https://github.com/user-attachments/assets/c01524ba-aea4-4f7b-85fd-88c83f4bfe05)

I think 'Cancel' and 'Create' buttons need to sit next to each other, but at least add some padding in between.

Once i click 'Create' button without adding anything on the form, the validations are triggered. I miss the part where the 'empty author list' is displayed somewhere - as no course can exist without an author.

2024-10-08 09:21 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.ts
> +  onSubmit() {
Once I add all required fields and course is created, there is an error on the console. Please take a look and fix that.
![image](https://github.com/user-attachments/assets/6216332e-8430-41bf-bde2-3b215b63e271)

2024-10-08 09:22 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.html
>          </div>
Error message for invalid email input is missing.

2024-10-08 09:24 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.scss
> +  border: 1px solid #cfcfcf;
can you please use a color variable here?

2024-10-08 09:24 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.scss
> +  border: 1px solid red;
color variable

2024-10-08 09:25 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.ts
Once I click login without entering credentials, the UI does not reflect the missing email and password. You might want to handle this to let the user know.

2024-10-08 09:27 UTC, TamasViczian commented on src/app/shared/components/registration-form/registration-form.component.html
> +        <input
Email validator is missing along withe the appropriate error message.

2024-10-08 09:28 UTC, TamasViczian commented on src/app/shared/components/registration-form/registration-form.component.scss
Please use the color variables.

2024-10-08 09:31 UTC, TamasViczian commented on src/app/shared/directives/email.directive.ts
> +    return emailValidator()(control);
Is there a reason why `emailValidator` fn is declared and not implemented here?

2024-10-08 09:32 UTC, TamasViczian commented on src/app/shared/pipes/duration.pipe.ts
> +  transform(minutes: number): string {
You might want to handle invalid duration inputs here.

2024-10-08 09:34 UTC, TamasViczian requested changes
Along with the individual review comments, please make sure you use the same approach for ButtonComponent. You can declare the texts separately and use them. Please avoid adding magic string directly to the input like: `<app-button [buttonText]="'someMagicSting'">`

2024-10-09 07:51 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.ts
Hmmm, I think this is not straightforward as it should be. On the template you assign the ngSubmit to the form and have the button click call another fn.
Can you please refactor this component (and it's template) to handle all scenarios in a single 'loin' or 'submit' fn?

2024-10-09 07:57 UTC, TamasViczian requested changes
I left a comment on the LoginComponent that needs an update.
The other thing I noticed is that you are declare button label texts in the component.ts files - as per needed. This should be handled in one place, similar to translations for example. Can you please introduce an exported variable or enumeration which will represent these texts as key - value pairs and use it across the application?

2024-10-09 08:06 UTC, mnstrdm commented on src/app/shared/components/login-form/login-form.component.ts
Ok.
I chose this, because the task description said, "... when the form has submitted status or control was touched". I wasn't sure, how strictly do I have to stick to the description. That's why I try to force the submitted status to change true.

2024-10-10 06:57 UTC, TamasViczian approved these changes
LGTM, approved.

2024-10-10 15:21 UTC, merged